// <auto-generated />
namespace BudgetApp.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class NewPaymentPlanChargeTableAndLinkage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewPaymentPlanChargeTableAndLinkage));
        
        string IMigrationMetadata.Id
        {
            get { return "201305100300127_NewPaymentPlanChargeTableAndLinkage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
